name:                synthetic
version:             0.1.0.0
# synopsis:
# description:
homepage:            https://github.com/sleexyz/synthetic#readme
license:             BSD3
author:              Sean Lee
maintainer:          freshdried@gmail.com
copyright:           BSD3
category:            Music
github: sleexyz/synthetic
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - process
  - random

library:
  source-dirs: src

executables:
  synthetic-example:
    main: Example.hs
    dependencies:
    - base
    - synthetic

tests:
  synthetic-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - synthetic
    - hspec
    - QuickCheck
